# Generated by Django 3.2.4 on 2021-06-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
