# Generated by Django 3.2.4 on 2021-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='id',
            new_name='rut',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default='.', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
