# Generated by Django 3.2.4 on 2021-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0005_alter_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
            ],
        ),
    ]
