# Generated by Django 3.2.4 on 2021-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0007_micarrito_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='micarrito',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
