# Generated by Django 3.2.4 on 2021-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0014_remove_micarrito_nomprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
