# Generated by Django 3.2.4 on 2021-07-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0018_alter_pedido_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='idpedido',
        ),
    ]
