# Generated by Django 3.2.4 on 2021-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0019_remove_pedido_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idpedido',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
