# Generated by Django 3.2.4 on 2021-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0023_rename_idpedido_pedido_idpedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='idpedidos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
