# Generated by Django 3.2.4 on 2021-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0024_auto_20210707_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
